### ISSUE TITLE
MacOS 13.2 + Xcode 14.2， run wda/tap function error

### ISSUE THREAD

**Issue by ssfanli** [appium/WebDriverAgent#683]
The mac system has been updated recently, and there is always an error when running automation. The information is as follows:
```
>>> el = c(label="设置").get()
>>> el.click()
Shell$ curl -X GET -d '' 'http+usbmux://00008030-000159591490802E:8100/session/CD862EF9-365B-49A4-A2AE-AB078C34774A/element/41000000-0000-0000-3700-000000000000/rect'
Return (132ms): {
  "value" : {
    "y" : 514,
    "x" : 221,
    "width" : 79,
    "height" : 105
  },
  "sessionId" : "CD862EF9-365B-49A4-A2AE-AB078C34774A"
}
Shell$ curl -X POST -d '{"x": 260, "y": 566}' 'http+usbmux://00008030-000159591490802E:8100/session/CD862EF9-365B-49A4-A2AE-AB078C34774A/wda/tap/0'
Return (262ms): {
  "value" : {
    "error" : "unknown error",
    "message" : "Invalid parameter not satisfying: allAttributesForKey != nil",
    "traceback" : "(\n\t0   CoreFoundation                      0x00000001abfbdc44 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 1256516\n\t1   libobjc.A.dylib                     0x00000001abcd80c8 objc_exception_throw + 60\n\t2   CoreFoundation                      0x00000001abeba75c 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 194396\n\t3   Foundation                          0x00000001ac2fb960 672CF0CB-4951-3B91-89DF-55E953AEA00F + 571744\n\t4   XCTAutomationSupport                0x0000000104c83600 -[XCElementSnapshot _fetchSimpleValueForKey:] + 1168\n\t5   XCTAutomationSupport                0x0000000104c85510 -[XCElementSnapshot systemAutomationProperties] + 100\n\t6   XCUIAutomation                      0x0000000104b631c0 __137+[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:]_block_invoke.19 + 212\n\t7   XCTestCore                          0x00000001049dccf4 +[XCTFuture futureWithDescription:block:] + 108\n\t8   XCUIAutomation                      0x0000000104b62d80 __137+[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:]_block_invoke_2 + 240\n\t9   XCTestCore                          0x0000000104a02e08 -[XCTContext _runActivityNamed:type:block:] + 196\n\t10  XCTestCore                          0x0000000104a01d20 -[XCTContext runInternalActivityNamed:block:] + 124\n\t11  XCUIAutomation                      0x0000000104b62c40 __137+[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:]_block_invoke + 204\n\t12  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t13  XCTestCore                          0x0000000104a03430 -[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 80\n\t14  XCUIAutomation                      0x0000000104b62a28 +[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:] + 364\n\t15  XCUIAutomation                      0x0000000104b639f4 -[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:error:] + 1044\n\t16  XCUIAutomation                      0x0000000104b63cfc __70-[XCUIElement(XCUIElementEventSynthesis) _dispatchEvent:eventBuilder:]_block_invoke + 116\n\t17  XCTestCore                          0x0000000104a02e08 -[XCTContext _runActivityNamed:type:block:] + 196\n\t18  XCTestCore                          0x0000000104a01d20 -[XCTContext runInternalActivityNamed:block:] + 124\n\t19  XCUIAutomation                      0x0000000104b63bcc -[XCUIElement(XCUIElementEventSynthesis) _dispatchEvent:eventBuilder:] + 228\n\t20  XCUIAutomation                      0x0000000104b901c0 -[XCUICoordinate(XCUICoordinateTouchEvents) tap] + 376\n\t21  WebDriverAgentLib                   0x000000010aa9dc68 +[FBElementCommands handleTap:] + 884\n\t22  WebDriverAgentLib                   0x000000010aa2be14 -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t23  WebDriverAgentLib                   0x000000010aa17a18 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 408\n\t24  WebDriverAgentLib                   0x000000010aa4e524 -[RoutingHTTPServer handleRoute:withRequest:response:] + 168\n\t25  WebDriverAgentLib                   0x000000010aa4f014 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t26  libdispatch.dylib                   0x00000001abc6500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300\n\t27  libdispatch.dylib                   0x00000001abc718e0 ED0789CD-8D80-39F4-9651-D8707D9C0337 + 63712\n\t28  libdispatch.dylib                   0x00000001abc6500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300\n\t29  libdispatch.dylib                   0x00000001abc70cd8 _dispatch_main_queue_callback_4CF + 968\n\t30  CoreFoundation                      0x00000001abf38e20 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 712224\n\t31  CoreFoundation                      0x00000001abf33b7c 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 691068\n\t32  CoreFoundation                      0x00000001abf33098 CFRunLoopRunSpecific + 480\n\t33  Foundation                          0x00000001ac278580 672CF0CB-4951-3B91-89DF-55E953AEA00F + 34176\n\t34  WebDriverAgentLib                   0x000000010aa16860 -[FBWebServer startServing] + 328\n\t35  WebDriverAgentRunner                0x000000010a84f980 -[UITestingUITests testRunner] + 80\n\t36  CoreFoundation                      0x00000001abfc4724 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 1283876\n\t37  CoreFoundation                      0x00000001abe8d280 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 8832\n\t38  XCTestCore                          0x0000000104a2c064 +[XCTFailableInvocation invokeStandardConventionInvocation:completion:] + 64\n\t39  XCTestCore                          0x0000000104a2c01c __90+[XCTFailableInvocation invokeInvocation:withTestMethodConvention:lastObservedErrorIssue:]_block_invoke_3 + 24\n\t40  XCTestCore                          0x0000000104a2ba54 __81+[XCTFailableInvocation invokeWithAsynchronousWait:lastObservedErrorIssue:block:]_block_invoke + 296\n\t41  XCTestCore                          0x00000001049edb88 +[XCTSwiftErrorObservation observeErrorsInBlock:] + 232\n\t42  XCTestCore                          0x0000000104a2b864 +[XCTFailableInvocation invokeWithAsynchronousWait:lastObservedErrorIssue:block:] + 184\n\t43  XCTestCore                          0x0000000104a2bddc +[XCTFailableInvocation invokeInvocation:withTestMethodConvention:lastObservedErrorIssue:] + 252\n\t44  XCTestCore                          0x0000000104a2c0d4 +[XCTFailableInvocation invokeInvocation:lastObservedErrorIssue:] + 68\n\t45  XCTestCore                          0x0000000104a1a020 __24-[XCTestCase invokeTest]_block_invoke_2 + 84\n\t46  XCTestCore                          0x00000001049fa4cc -[XCTMemoryChecker _assertInvalidObjectsDeallocatedAfterScope:] + 76\n\t47  XCTestCore                          0x0000000104a232f0 -[XCTestCase assertInvalidObjectsDeallocatedAfterScope:] + 88\n\t48  XCTestCore                          0x0000000104a19fa8 __24-[XCTestCase invokeTest]_block_invoke.78 + 144\n\t49  XCTestCore                          0x00000001049e6d8c -[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:] + 160\n\t50  XCTestCore                          0x0000000104a19b94 -[XCTestCase invokeTest] + 684\n\t51  XCTestCore                          0x0000000104a1b0e4 __26-[XCTestCase performTest:]_block_invoke.119 + 32\n\t52  XCTestCore                          0x00000001049e6d8c -[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:] + 160\n\t53  XCTestCore                          0x0000000104a1ac38 __26-[XCTestCase performTest:]_block_invoke.110 + 456\n\t54  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t55  XCTestCore                          0x0000000104a03270 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140\n\t56  XCTestCore                          0x0000000104a1a8d0 -[XCTestCase performTest:] + 248\n\t57  XCTestCore                          0x00000001049d6c5c -[XCTest runTest] + 44\n\t58  XCTestCore                          0x0000000104a05bc8 -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64\n\t59  XCTestCore                          0x0000000104a05aac __27-[XCTestSuite performTest:]_block_invoke + 160\n\t60  XCTestCore                          0x0000000104a055fc __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40\n\t61  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t62  XCTestCore                          0x0000000104a03270 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140\n\t63  XCTestCore                          0x0000000104a055a4 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152\n\t64  XCTestCore                          0x0000000104a057d8 -[XCTestSuite performTest:] + 188\n\t65  XCTestCore                          0x00000001049d6c5c -[XCTest runTest] + 44\n\t66  XCTestCore                          0x0000000104a05bc8 -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64\n\t67  XCTestCore                          0x0000000104a05aac __27-[XCTestSuite performTest:]_block_invoke + 160\n\t68  XCTestCore                          0x0000000104a055fc __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40\n\t69  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t70  XCTestCore                          0x0000000104a03270 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140\n\t71  XCTestCore                          0x0000000104a055a4 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152\n\t72  XCTestCore                          0x0000000104a057d8 -[XCTestSuite performTest:] + 188\n\t73  XCTestCore                          0x00000001049d6c5c -[XCTest runTest] + 44\n\t74  XCTestCore                          0x0000000104a05bc8 -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64\n\t75  XCTestCore                          0x0000000104a05aac __27-[XCTestSuite performTest:]_block_invoke + 160\n\t76  XCTestCore                          0x0000000104a055fc __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40\n\t77  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t78  XCTestCore                          0x0000000104a03270 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140\n\t79  XCTestCore                          0x0000000104a055a4 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152\n\t80  XCTestCore                          0x0000000104a057d8 -[XCTestSuite performTest:] + 188\n\t81  XCTestCore                          0x00000001049d6c5c -[XCTest runTest] + 44\n\t82  XCTestCore                          0x00000001049d84d0 __89-[XCTTestRunSession executeTestsWithIdentifiers:skippingTestsWithIdentifiers:completion:]_block_invoke + 100\n\t83  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t84  XCTestCore                          0x0000000104a03270 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140\n\t85  XCTestCore                          0x00000001049d83cc -[XCTTestRunSession executeTestsWithIdentifiers:skippingTestsWithIdentifiers:completion:] + 252\n\t86  XCTestCore                          0x0000000104a37f98 __72-[XCTExecutionWorker enqueueTestIdentifiersToRun:testIdentifiersToSkip:]_block_invoke_2 + 108\n\t87  XCTestCore                          0x0000000104a380d4 -[XCTExecutionWorker runWithError:] + 100\n\t88  XCTestCore                          0x0000000104a00874 __25-[XCTestDriver _runTests]_block_invoke.188 + 52\n\t89  XCTestCore                          0x00000001049e0654 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 256\n\t90  XCTestCore                          0x0000000104a004d8 -[XCTestDriver _runTests] + 1016\n\t91  XCTestCore                          0x00000001049d7144 _XCTestMain + 84\n\t92  WebDriverAgentRunner-Runner         0x0000000104635d0c -[_XCTRunnerAppDelegate application:didFinishLaunchingWithOptions:] + 0\n\t93  CoreFoundation                      0x00000001abf3907c 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 712828\n\t94  CoreFoundation                      0x00000001abf38800 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 710656\n\t95  CoreFoundation                      0x00000001abf33800 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 690176\n\t96  CoreFoundation                      0x00000001abf33098 CFRunLoopRunSpecific + 480\n\t97  GraphicsServices                    0x00000001b609d534 GSEventRunModal + 108\n\t98  UIKitCore                           0x00000001b00537ac UIApplicationMain + 1940\n\t99  WebDriverAgentRunner-Runner         0x0000000104635ec0 main + 160\n\t100 libdyld.dylib                       0x00000001abdb2f30 326A0541-5D13-3687-97EC-C58FACB384EE + 3888\n)"
  },
  "sessionId" : "CD862EF9-365B-49A4-A2AE-AB078C34774A"
}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/wda/__init__.py", line 1721, in click
    self._session.click(x, y)
  File "/opt/homebrew/lib/python3.9/site-packages/wda/__init__.py", line 920, in click
    return self.tap(x, y)
  File "/opt/homebrew/lib/python3.9/site-packages/wda/__init__.py", line 898, in tap
    return self._session_http.post('/wda/tap/0', dict(x=x, y=y))
  File "/opt/homebrew/lib/python3.9/site-packages/wda/utils.py", line 47, in _inner
    return fn(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/wda/__init__.py", line 460, in _fetch
    response = httpdo(url, method, data, timeout)
  File "/opt/homebrew/lib/python3.9/site-packages/wda/__init__.py", line 130, in httpdo
    return _unsafe_httpdo(url, method, data, timeout)
  File "/opt/homebrew/lib/python3.9/site-packages/wda/__init__.py", line 186, in _unsafe_httpdo
    raise errCls(status, value)
wda.exceptions.WDAUnknownError: WDARequestError(status=110, value={'error': 'unknown error', 'message': 'Invalid parameter not satisfying: allAttributesForKey != nil'})
```
* MacOS: 13.2
* Xcode: 14.2
* WDA: v4.13.1
* WDA python client：[openatx/facebook-wda](https://github.com/openatx/facebook-wda)

**Comment by ssfanli** [comment]
wda stack
```
	0   CoreFoundation                      0x00000001abfbdc44 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 1256516
	1   libobjc.A.dylib                     0x00000001abcd80c8 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001abeba75c 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 194396
	3   Foundation                          0x00000001ac2fb960 672CF0CB-4951-3B91-89DF-55E953AEA00F + 571744
	4   XCTAutomationSupport                0x0000000104c83600 -[XCElementSnapshot _fetchSimpleValueForKey:] + 1168
	5   XCTAutomationSupport                0x0000000104c85510 -[XCElementSnapshot systemAutomationProperties] + 100
	6   XCUIAutomation                      0x0000000104b631c0 __137+[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:]_block_invoke.19 + 212
	7   XCTestCore                          0x00000001049dccf4 +[XCTFuture futureWithDescription:block:] + 108
	8   XCUIAutomation                      0x0000000104b62d80 __137+[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:]_block_invoke_2 + 240
	9   XCTestCore                          0x0000000104a02e08 -[XCTContext _runActivityNamed:type:block:] + 196
	10  XCTestCore                          0x0000000104a01d20 -[XCTContext runInternalActivityNamed:block:] + 124
	11  XCUIAutomation                      0x0000000104b62c40 __137+[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:]_block_invoke + 204
	12  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172
	13  XCTestCore                          0x0000000104a03430 -[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 80
	14  XCUIAutomation                      0x0000000104b62a28 +[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:] + 364
	15  XCUIAutomation                      0x0000000104b639f4 -[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:error:] + 1044
	16  XCUIAutomation                      0x0000000104b63cfc __70-[XCUIElement(XCUIElementEventSynthesis) _dispatchEvent:eventBuilder:]_block_invoke + 116
	17  XCTestCore                          0x0000000104a02e08 -[XCTContext _runActivityNamed:type:block:] + 196
	18  XCTestCore                          0x0000000104a01d20 -[XCTContext runInternalActivityNamed:block:] + 124
	19  XCUIAutomation                      0x0000000104b63bcc -[XCUIElement(XCUIElementEventSynthesis) _dispatchEvent:eventBuilder:] + 228
	20  XCUIAutomation                      0x0000000104b901c0 -[XCUICoordinate(XCUICoordinateTouchEvents) tap] + 376
	21  WebDriverAgentLib                   0x000000010aa9dc68 +[FBElementCommands handleTap:] + 884
	22  WebDriverAgentLib                   0x000000010aa2be14 -[FBRoute_TargetAction mountRequest:intoResponse:] + 168
	23  WebDriverAgentLib                   0x000000010aa17a18 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 408
	24  WebDriverAgentLib                   0x000000010aa4e524 -[RoutingHTTPServer handleRoute:withRequest:response:] + 168
	25  WebDriverAgentLib                   0x000000010aa4f014 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64
	26  libdispatch.dylib                   0x00000001abc6500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300
	27  libdispatch.dylib                   0x00000001abc718e0 ED0789CD-8D80-39F4-9651-D8707D9C0337 + 63712
	28  libdispatch.dylib                   0x00000001abc6500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300
	29  libdispatch.dylib                   0x00000001abc70cd8 _dispatch_main_queue_callback_4CF + 968
	30  CoreFoundation                      0x00000001abf38e20 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 712224
	31  CoreFoundation                      0x00000001abf33b7c 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 691068
	32  CoreFoundation                      0x00000001abf33098 CFRunLoopRunSpecific + 480
	33  Foundation                          0x00000001ac278580 672CF0CB-4951-3B91-89DF-55E953AEA00F + 34176
	34  WebDriverAgentLib                   0x000000010aa16860 -[FBWebServer startServing] + 328
	35  WebDriverAgentRunner                0x000000010a84f980 -[UITestingUITests testRunner] + 80
	36  CoreFoundation                      0x00000001abfc4724 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 1283876
	37  CoreFoundation                      0x00000001abe8d280 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 8832
	38  XCTestCore                          0x0000000104a2c064 +[XCTFailableInvocation invokeStandardConventionInvocation:completion:] + 64
	39  XCTestCore                          0x0000000104a2c01c __90+[XCTFailableInvocation invokeInvocation:withTestMethodConvention:lastObservedErrorIssue:]_block_invoke_3 + 24
	40  XCTestCore                          0x0000000104a2ba54 __81+[XCTFailableInvocation invokeWithAsynchronousWait:lastObservedErrorIssue:block:]_block_invoke + 296
	41  XCTestCore                          0x00000001049edb88 +[XCTSwiftErrorObservation observeErrorsInBlock:] + 232
	42  XCTestCore                          0x0000000104a2b864 +[XCTFailableInvocation invokeWithAsynchronousWait:lastObservedErrorIssue:block:] + 184
	43  XCTestCore                          0x0000000104a2bddc +[XCTFailableInvocation invokeInvocation:withTestMethodConvention:lastObservedErrorIssue:] + 252
	44  XCTestCore                          0x0000000104a2c0d4 +[XCTFailableInvocation invokeInvocation:lastObservedErrorIssue:] + 68
	45  XCTestCore                          0x0000000104a1a020 __24-[XCTestCase invokeTest]_block_invoke_2 + 84
	46  XCTestCore                          0x00000001049fa4cc -[XCTMemoryChecker _assertInvalidObjectsDeallocatedAfterScope:] + 76
	47  XCTestCore                          0x0000000104a232f0 -[XCTestCase assertInvalidObjectsDeallocatedAfterScope:] + 88
	48  XCTestCore                          0x0000000104a19fa8 __24-[XCTestCase invokeTest]_block_invoke.78 + 144
	49  XCTestCore                          0x00000001049e6d8c -[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:] + 160
	50  XCTestCore                          0x0000000104a19b94 -[XCTestCase invokeTest] + 684
	51  XCTestCore                          0x0000000104a1b0e4 __26-[XCTestCase performTest:]_block_invoke.119 + 32
	52  XCTestCore                          0x00000001049e6d8c -[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:] + 160
	53  XCTestCore                          0x0000000104a1ac38 __26-[XCTestCase performTest:]_block_invoke.110 + 456
	54  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172
	55  XCTestCore                          0x0000000104a03270 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140
	56  XCTestCore                          0x0000000104a1a8d0 -[XCTestCase performTest:] + 248
	57  XCTestCore                          0x00000001049d6c5c -[XCTest runTest] + 44
	58  XCTestCore                          0x0000000104a05bc8 -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64
	59  XCTestCore                          0x0000000104a05aac __27-[XCTestSuite performTest:]_block_invoke + 160
	60  XCTestCore                          0x0000000104a055fc __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40
	61  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172
	62  XCTestCore                          0x0000000104a03270 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140
	63  XCTestCore                          0x0000000104a055a4 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152
	64  XCTestCore                          0x0000000104a057d8 -[XCTestSuite performTest:] + 188
	65  XCTestCore                          0x00000001049d6c5c -[XCTest runTest] + 44
	66  XCTestCore                          0x0000000104a05bc8 -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64
	67  XCTestCore                          0x0000000104a05aac __27-[XCTestSuite performTest:]_block_invoke + 160
	68  XCTestCore                          0x0000000104a055fc __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40
	69  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172
	70  XCTestCore                          0x0000000104a03270 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140
	71  XCTestCore                          0x0000000104a055a4 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152
	72  XCTestCore                          0x0000000104a057d8 -[XCTestSuite performTest:] + 188
	73  XCTestCore                          0x00000001049d6c5c -[XCTest runTest] + 44
	74  XCTestCore                          0x0000000104a05bc8 -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64
	75  XCTestCore                          0x0000000104a05aac __27-[XCTestSuite performTest:]_block_invoke + 160
	76  XCTestCore                          0x0000000104a055fc __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40
	77  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172
	78  XCTestCore                          0x0000000104a03270 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140
	79  XCTestCore                          0x0000000104a055a4 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152
	80  XCTestCore                          0x0000000104a057d8 -[XCTestSuite performTest:] + 188
	81  XCTestCore                          0x00000001049d6c5c -[XCTest runTest] + 44
	82  XCTestCore                          0x00000001049d84d0 __89-[XCTTestRunSession executeTestsWithIdentifiers:skippingTestsWithIdentifiers:completion:]_block_invoke + 100
	83  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172
	84  XCTestCore                          0x0000000104a03270 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140
	85  XCTestCore                          0x00000001049d83cc -[XCTTestRunSession executeTestsWithIdentifiers:skippingTestsWithIdentifiers:completion:] + 252
	86  XCTestCore                          0x0000000104a37f98 __72-[XCTExecutionWorker enqueueTestIdentifiersToRun:testIdentifiersToSkip:]_block_invoke_2 + 108
	87  XCTestCore                          0x0000000104a380d4 -[XCTExecutionWorker runWithError:] + 100
	88  XCTestCore                          0x0000000104a00874 __25-[XCTestDriver _runTests]_block_invoke.188 + 52
	89  XCTestCore                          0x00000001049e0654 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 256
	90  XCTestCore                          0x0000000104a004d8 -[XCTestDriver _runTests] + 1016
	91  XCTestCore                          0x00000001049d7144 _XCTestMain + 84
	92  WebDriverAgentRunner-Runner         0x0000000104635d0c -[_XCTRunnerAppDelegate application:didFinishLaunchingWithOptions:] + 0
	93  CoreFoundation                      0x00000001abf3907c 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 712828
	94  CoreFoundation                      0x00000001abf38800 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 710656
	95  CoreFoundation                      0x00000001abf33800 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 690176
	96  CoreFoundation                      0x00000001abf33098 CFRunLoopRunSpecific + 480
	97  GraphicsServices                    0x00000001b609d534 GSEventRunModal + 108
	98  UIKitCore                           0x00000001b00537ac UIApplicationMain + 1940
	99  WebDriverAgentRunner-Runner         0x0000000104635ec0 main + 160
	100 libdyld.dylib                       0x00000001abdb2f30 326A0541-5D13-3687-97EC-C58FACB384EE + 3888
```

**Comment by KazuCocoa** [comment]
Only when you build WDA with macOS 13.2? Both a real device and simulator? What about `/click` endpoint? (e.g. POST `session/CD862EF9-365B-49A4-A2AE-AB078C34774A/element/41000000-0000-0000-3700-000000000000/click` to the WDA)


Just tried with macOS 12 x Xcode 14.2, but no such errors with a simulator.

**Comment by KazuCocoa** [comment]
@Dan-Maor @mykola-mokhnach Have you seen this error?
i don't have macOS 13.2 right now, so haven't checked with macOS 13.2.

**Comment by Dan-Maor** [comment]
I currently only have access to a Mac running MacOS 13.3.1 and an iPhone running iOS 15.7, and am not able to reproduce the issue with either Xcode 14.2 or 14.3.

Given that the stack trace shows that the faulting action is the public API `-[XCUICoordinate tap]` it looks like either an internal XCUITest issue or a problem generating the `XCUICoordinate` object (I lean towards the former).

Which iOS version is your device running?
If possible - can you please add the WDA Xcode output?

**Comment by KazuCocoa** [comment]
Just a note.
I quickly checked with macOS 13.2.1 x Xcode 14.3 x iOS 16.4 simulator (with latest WDA master, started from the Xcode), but no issue occurred in the mobile:tap and click.

I'll try with a real device tomorrow (may be late)

**Comment by ssfanli** [comment]
Thanks！I found this error when using real device, and haven't checked with simulator yet.
real device is iPhone XR/iOS12.3.1
I will add WDA Xcode log tomorrow.

**Comment by KazuCocoa** [comment]
Tried with a real device, iPad 16.5 beta, with macOS 13.2 x Xcode 14.2. It had no such error. (iOS 12.5.6 also had no issue, btw.)

**Comment by mykola-mokhnach** [comment]
Unfortunately iOS12.3.1 is too old and we do not support it anymore. We only target the current and the previous releases (e.g. 16 and 15). Try some older (maybe much older) versions of the driver to make that work with ancient mobile OS versions.

Closed as not an issue

**Comment by nanoscopic** [comment]
> Unfortunately iOS12.3.1 is too old and we do not support it anymore. We only target the current and the previous releases (e.g. 16 and 15). Try some older (maybe much older) versions of the driver to make that work with ancient mobile OS versions.
> 
> Closed as not an issue

@mykola-mokhnach Could you clarify who "we" is here?
Are you stating that Appium doesn't support versions of iOS before iOS 15?

Documentation seems to say iOS 9 and up.
https://dpgraham.github.io/docs/en/about-appium/platform-support/

May I quote officially that Appium is taking the position of not supporting iOS before iOS 15?

**Comment by KazuCocoa** [comment]
It's wrong page. https://appium.github.io/appium-xcuitest-driver/latest/installation/requirements/ is official one.

**Comment by jlipps** [comment]
Yeah pretty sure our stance has been that _current_ versions of appium's iOS driver only support the two most recent iOS releases.

> Generally, the driver aims to support at least two latest major Xcode and iOS versions.
